create table employees(
id serial primary key,
employee_name Varchar(50) not null
);
insert into employees(employee_name) 
values ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'),
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'),
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'),
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'),
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'),
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'),
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike'), 
       ('jonn'), 
       ('korol'), 
       ('petr'), 
       ('liza'), 
       ('mike');
select * from employees ;
create table salary(
id serial primary key,
monthly_salary int not null);
insert into salary(monthly_salary)
values (1000), (1100), (1200), (1300), (1400), (1500), (1600), (1700), (1800),
(1900), (2000), (2100), (2200), (2300), (2400);
select * from salary;
create table employee_salary(
id serial primary key,
employee_id int unique not null ,
salary_id int not null);
select * from employee_salary;
insert into employee_salary (id, employee_id, salary_id)
values (default, 7, 4),
       (default, 6, 10),
       (default, 5, 10),
       (default, 4, 10),
       (default, 3, 4),
       (default, 2, 4),
       (default, 1, 4),
       (default, 8, 14),
       (default, 9, 11),
       (default, 10, 12),
       (default, 17, 4),
       (default, 16, 13),
       (default, 15, 9),
       (default, 14, 3),
       (default, 13, 4),
       (default, 12, 4),
       (default, 11, 4),
       (default, 18, 15),
       (default, 19, 11),
       (default, 20, 12),
       (default, 27, 4),
       (default, 26, 10),
       (default, 25, 10),
       (default, 24, 10),
       (default, 23, 4),
       (default, 22, 4),
       (default, 21, 4),
       (default, 28, 14),
       (default, 29, 11),
       (default, 30, 12),
       (default, 97, 4),
       (default, 96, 11),
       (default, 95, 12),
       (default, 94, 1),
       (default, 93, 4),
       (default, 92, 4),
       (default, 91, 4),
       (default, 98, 14),
       (default, 99, 15),
       (default, 90, 6);
create table roles (
id serial primary key,
role_name int unique not null);
alter table roles
alter column role_name type varchar (30);
insert into roles(id, role_name)
values (default, 'Junior Python developer'),
       (default, 'Middle Python developer'),
       (default, 'Senior Python developer'),
       (default, 'Junior Java developer'),
       (default, 'Middle Java developer'),
       (default, 'Senior Java developer'),
       (default, 'Junior JavaScript developer'),
       (default, 'Middle JavaScript developer'),
       (default, 'Senior JavaScript developer'),
       (default, 'Junior Manual QA engineer'),
       (default, 'Middle Manual QA engineer'),
       (default, 'Senior Manual QA engineer'),
       (default, 'Junior Automation QA engineer'),
       (default, 'Middle Automation QA engineer'),
       (default, 'Senior Automation QA engineer'),
       (default, 'Progect Manager'),
       (default, 'Designer'),
       (default, 'HR'),
       (default, 'CEO'),
       (default, 'Sales Manager');
create table roles_employee(
id serial primary key,
employee_id int unique not null,
role_id int not null,
foreign key (employee_id)
references employees (id),
foreign key (role_id)
references roles (id));
insert into roles_employee (id, employee_id, role_id)
values (default, 65, 20),
       (default, 64, 10),
       (default, 63, 12),
       (default, 62, 15),
       (default, 61, 17),
       (default, 60, 2),
       (default, 66, 1),
       (default, 67, 12),
       (default, 68, 5),
       (default, 69, 7),
       (default, 55, 2),
       (default, 54, 1),
       (default, 53, 12),
       (default, 52, 5),
       (default, 51, 7),
       (default, 50, 20),
       (default, 56, 11),
       (default, 57, 13),
       (default, 58, 5),
       (default, 59, 17),
       (default, 45, 20),
       (default, 44, 10),
       (default, 43, 12),
       (default, 42, 15),
       (default, 41, 17),
       (default, 40, 2),
       (default, 46, 1),
       (default, 47, 12),
       (default, 48, 5),
       (default, 49, 7),
       (default, 35, 2),
       (default, 34, 1),
       (default, 33, 12),
       (default, 32, 5),
       (default, 31, 7),
       (default, 30, 20),
       (default, 36, 11),
       (default, 37, 13),
       (default, 38, 5),
       (default, 39, 17);
select * from roles_employee;     
